knp_paginator:
    page_range: 5                      # Nombre de pages affichées dans la pagination
    default_options:
        page_name: page               # Nom du paramètre de la page
        sort_field_name: sort         # Nom du paramètre de tri
        sort_direction_name: direction # Nom du paramètre de direction de tri
        distinct: true                # Activer la récupération de résultats distincts
    template:
        pagination: '@KnpPaginator/Pagination/sliding.html.twig'
        sortable: '@KnpPaginator/Pagination/sortable_link.html.twig'
