<?php

namespace ContainerY5mXBTA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_25Z2SSService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.25_Z2SS' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.25_Z2SS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'dompdf' => ['privates', 'Dompdf\\Dompdf', 'getDompdfService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'dompdf' => 'Dompdf\\Dompdf',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
