<?php

namespace ContainerY5mXBTA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KZrdicpService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.KZrdicp' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KZrdicp'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'codeRepository' => ['privates', 'App\\Repository\\CodeRepository', 'getCodeRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'codeRepository' => 'App\\Repository\\CodeRepository',
            'entityManager' => '?',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
