<?php

namespace ContainerJx7aFVq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UBDwBpqService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.uBDwBpq' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.uBDwBpq'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'codeRepository' => ['privates', 'App\\Repository\\CodeRepository', 'getCodeRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'codeRepository' => 'App\\Repository\\CodeRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
