<?php

namespace ContainerZDDbnjb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDompdfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Dompdf\Dompdf' shared autowired service.
     *
     * @return \Dompdf\Dompdf
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'dompdf'.\DIRECTORY_SEPARATOR.'dompdf'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Dompdf.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'dompdf'.\DIRECTORY_SEPARATOR.'dompdf'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Options.php';

        return $container->privates['Dompdf\\Dompdf'] = new \Dompdf\Dompdf(new \Dompdf\Options());
    }
}
