<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLvoo2P9\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLvoo2P9/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLvoo2P9.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLvoo2P9\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLvoo2P9\App_KernelDevDebugContainer([
    'container.build_hash' => 'Lvoo2P9',
    'container.build_id' => '9cb0f84f',
    'container.build_time' => 1683119333,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLvoo2P9');
