<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHn9oTEk\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHn9oTEk/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHn9oTEk.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHn9oTEk\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHn9oTEk\App_KernelDevDebugContainer([
    'container.build_hash' => 'Hn9oTEk',
    'container.build_id' => '5be1d59e',
    'container.build_time' => 1681772642,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHn9oTEk');
