<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMsEl0PP\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMsEl0PP/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMsEl0PP.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMsEl0PP\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMsEl0PP\App_KernelDevDebugContainer([
    'container.build_hash' => 'MsEl0PP',
    'container.build_id' => '50900b4f',
    'container.build_time' => 1683151790,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMsEl0PP');
